# Generated by Django 4.1.5 on 2023-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
